---
services:
  orb-runner:
    build:
      dockerfile: Dockerfile
    environment:
      - PORT=38899
      - HOST=10.20.0.4
      - refreshSeconds=60
      - betterColorMode=true
      - lightDimming=50